### ISSUE TITLE
add support for golang

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/judge-workers#14]

**Comment by VibhorCodecianGupta** [comment]
@championswimmer done in #16, travis passing in commit [e41c1da](https://github.com/coding-blocks/judge-workers/pull/16/commits/e41c1da5c24ce28b46df949e53c7717f72bba453). However I accidentally messed up the git history, so am opening a fresh PR with the changes.

**Comment by championswimmer** [comment]
@VibhorCodecianGupta your PR looks good. for the full bounty claim you have to add support here too https://github.com/coding-blocks/judge-taskmaster/issues/17

**Comment by VibhorCodecianGupta** [comment]
Was my next stop anyway, will do!

**Comment by codefeeder** [comment]
@championswimmer is this issue still open for contribution?
