### ISSUE TITLE
fix mono not found issue on csharp

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/judge-workers#38]

**Comment by VibhorCodecianGupta** [comment]
@championswimmer @abhishek97 

found this image, works fine. Not Alpine though, Alpine seems to have just version `5.10.0.179-r1` which seems to be buggy.

Image: https://github.com/mono/docker
Looks good?

**Comment by championswimmer** [comment]
Let us do this  https://hub.docker.com/_/mono/
