### ISSUE TITLE
add support for Ruby

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/judge-workers#4]
- [ ] add the docker container and compile + run scripts here
- [ ] add run spec test on taskmaster https://github.com/coding-blocks/judge-taskmaster/issues/11

**Comment by kapillamba4** [comment]
Pull request for this issue: #5

**Comment by Satyabrat35** [comment]
PR for this issue #8

**Comment by championswimmer** [comment]
note the bounty is subject the completition of both the sub tasks

**Comment by aggarwalpulkit596** [comment]
Pr for this issue #7 and sub part of this pr coding-blocks/judge-taskmaster#12

**Comment by championswimmer** [comment]
sorry running busy. i'll take a look at the prs by tomorrow
