### ISSUE TITLE
fix failing kotlin test

### ISSUE THREAD

**Issue by gurrrung** [coding-blocks/judge-workers#50]
get the project to green build

**Comment by gurrrung** [comment]
@championswimmer Assign some Bounty if you think this work deserves some. Build is green now.

**Comment by championswimmer** [comment]
Assigned bounty on the PR itself. :) 

You can claim for 100

**Comment by gurrrung** [comment]
Master branch is passing all tests. Why does it still shows build failing?
https://travis-ci.org/github/coding-blocks/judge-workers
